// Unit tests for the release version-bump script (node --test .claude/skills/bump/).
// Each test builds a throwaway fixture repo in the OS temp dir and injects a
// fake exec, so nothing touches the real manifests and npm/cargo never run.

import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import { BumpError, runBump } from './bump.mjs';

// package.json and its lock are CRLF on disk; the src-tauri files are LF
// (pinned eol=lf) — the fixtures mirror that split so the byte-preservation
// tests mean something.
const PKG = [
  '{',
  '  "name": "wikilens",',
  '  "private": true,',
  '  "version": "0.1.0",',
  '  "type": "module",',
  '  "scripts": {',
  '    "bump": "node .claude/skills/bump/bump.mjs"',
  '  }',
  '}',
  '',
].join('\r\n');

const CARGO = [
  '[package]',
  'name = "wikilens"',
  'version = "0.1.0"',
  'edition = "2021"',
  '',
  '[lib]',
  'name = "wikilens_lib"',
  '',
  '[dependencies]',
  'tauri = { version = "2", features = ["tray-icon"] }',
  'serde = { version = "1", features = ["derive"] }',
  '',
  '[dependencies.image]',
  'version = "0.25"',
  'default-features = false',
  '',
].join('\n');

const CONF = [
  '{',
  '  "productName": "WikiLens",',
  '  "version": "0.1.0",',
  '  "bundle": {',
  '    "windows": {',
  '      "wix": {',
  '        "version": "9.9.9"',
  '      }',
  '    }',
  '  }',
  '}',
  '',
].join('\n');

const PKG_LOCK = [
  '{',
  '  "name": "wikilens",',
  '  "version": "0.1.0",',
  '  "lockfileVersion": 3,',
  '  "packages": {',
  '    "": {',
  '      "name": "wikilens",',
  '      "version": "0.1.0"',
  '    },',
  '    "node_modules/react": {',
  '      "version": "18.3.1"',
  '    }',
  '  }',
  '}',
  '',
].join('\r\n');

const CARGO_LOCK = [
  '# This file is automatically @generated by Cargo.',
  'version = 4',
  '',
  '[[package]]',
  'name = "serde"',
  'version = "1.0.200"',
  '',
  '[[package]]',
  'name = "wikilens"',
  'version = "0.1.0"',
  'dependencies = [',
  ' "serde",',
  ']',
  '',
].join('\n');

function makeRepo(t, { pkg = PKG, cargo = CARGO, conf = CONF } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'bump-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  mkdirSync(join(root, 'src-tauri'));
  if (pkg !== null) writeFileSync(join(root, 'package.json'), pkg);
  if (cargo !== null) writeFileSync(join(root, 'src-tauri', 'Cargo.toml'), cargo);
  if (conf !== null) writeFileSync(join(root, 'src-tauri', 'tauri.conf.json'), conf);
  writeFileSync(join(root, 'package-lock.json'), PKG_LOCK);
  writeFileSync(join(root, 'src-tauri', 'Cargo.lock'), CARGO_LOCK);
  return root;
}

// Fake exec that does what the real tools would: rewrite the lock the invoked
// command owns to the manifest's new version. Optionally records its calls.
const fakeRefresh = (root, next, calls = []) => (tool, args, cwd) => {
  calls.push({ tool, args, cwd });
  if (tool === 'npm') {
    const path = join(root, 'package-lock.json');
    writeFileSync(path, readFileSync(path, 'utf8').replaceAll('"version": "0.1.0"', `"version": "${next}"`));
  } else {
    const path = join(root, 'src-tauri', 'Cargo.lock');
    writeFileSync(
      path,
      readFileSync(path, 'utf8').replace('name = "wikilens"\nversion = "0.1.0"', `name = "wikilens"\nversion = "${next}"`),
    );
  }
  return { status: 0 };
};

const bump = (root, next = '0.2.0') => runBump(next, { root, exec: fakeRefresh(root, next) });

const readRepo = (root, rel) => readFileSync(join(root, ...rel.split('/')), 'utf8');

test('rewrites the version in all three manifests and reports old → new per file', (t) => {
  const root = makeRepo(t);
  const report = bump(root);
  assert.equal(report.previous, '0.1.0');
  assert.equal(report.next, '0.2.0');
  assert.deepEqual(report.manifests, [
    { path: 'package.json', from: '0.1.0', to: '0.2.0' },
    { path: 'src-tauri/Cargo.toml', from: '0.1.0', to: '0.2.0' },
    { path: 'src-tauri/tauri.conf.json', from: '0.1.0', to: '0.2.0' },
  ]);
  assert.ok(readRepo(root, 'package.json').includes('"version": "0.2.0"'));
  assert.ok(readRepo(root, 'src-tauri/Cargo.toml').includes('version = "0.2.0"'));
  assert.ok(readRepo(root, 'src-tauri/tauri.conf.json').includes('"version": "0.2.0"'));
});

test('preserves CRLF in package.json and LF in the src-tauri manifests byte-for-byte', (t) => {
  const root = makeRepo(t);
  bump(root);
  assert.equal(readRepo(root, 'package.json'), PKG.replace('"version": "0.1.0"', '"version": "0.2.0"'));
  assert.equal(readRepo(root, 'src-tauri/Cargo.toml'), CARGO.replace('version = "0.1.0"', 'version = "0.2.0"'));
  assert.equal(
    readRepo(root, 'src-tauri/tauri.conf.json'),
    CONF.replace('"version": "0.1.0"', '"version": "0.2.0"'),
  );
});

test('leaves Cargo.toml dependency version pins untouched', (t) => {
  const root = makeRepo(t);
  bump(root);
  const cargo = readRepo(root, 'src-tauri/Cargo.toml');
  assert.ok(cargo.includes('tauri = { version = "2", features = ["tray-icon"] }'));
  assert.ok(cargo.includes('serde = { version = "1", features = ["derive"] }'));
  assert.ok(cargo.includes('[dependencies.image]\nversion = "0.25"'));
});

test('a nested "version" key in tauri.conf.json is not the one rewritten', (t) => {
  const root = makeRepo(t);
  bump(root);
  const conf = readRepo(root, 'src-tauri/tauri.conf.json');
  assert.ok(conf.includes('  "version": "0.2.0"'));
  assert.ok(conf.includes('"version": "9.9.9"'));
});

test('mismatched manifest versions abort before anything is touched', (t) => {
  const conf = CONF.replace('"version": "0.1.0"', '"version": "0.0.9"');
  const root = makeRepo(t, { conf });
  const calls = [];
  assert.throws(
    () => runBump('0.2.0', { root, exec: fakeRefresh(root, '0.2.0', calls) }),
    (err) => err instanceof BumpError && /disagree/.test(err.message) && /tauri\.conf\.json = 0\.0\.9/.test(err.message),
  );
  assert.equal(calls.length, 0);
  assert.equal(readRepo(root, 'package.json'), PKG);
  assert.equal(readRepo(root, 'src-tauri/Cargo.toml'), CARGO);
  assert.equal(readRepo(root, 'src-tauri/tauri.conf.json'), conf);
});

test('rejects a version that is not plain X.Y.Z', (t) => {
  const root = makeRepo(t);
  for (const bad of ['0.2', 'v0.2.0', '0.2.0-rc.1', '01.2.3', '0.2.0.1']) {
    assert.throws(() => bump(root, bad), /not a plain X\.Y\.Z version/);
  }
  // Directly on runBump — the local helper's default parameter would swallow
  // the undefined case.
  for (const empty of ['', undefined]) {
    assert.throws(() => runBump(empty, { root, exec: () => ({ status: 0 }) }), /usage: npm run bump/);
  }
});

test('rejects bumping to the version the manifests already have', (t) => {
  const root = makeRepo(t);
  assert.throws(() => bump(root, '0.1.0'), /already at 0\.1\.0/);
});

test('a missing manifest aborts with the file named', (t) => {
  const root = makeRepo(t, { conf: null });
  assert.throws(() => bump(root), /tauri\.conf\.json: not found/);
});

test('a downgrade is allowed and reported like any bump', (t) => {
  const root = makeRepo(t);
  const report = bump(root, '0.0.9');
  assert.equal(report.previous, '0.1.0');
  assert.equal(report.next, '0.0.9');
  assert.ok(readRepo(root, 'package.json').includes('"version": "0.0.9"'));
});

test('refreshes locks with the right commands in the right directories', (t) => {
  const root = makeRepo(t);
  const calls = [];
  runBump('0.2.0', { root, exec: fakeRefresh(root, '0.2.0', calls) });
  assert.deepEqual(calls, [
    { tool: 'npm', args: ['install', '--package-lock-only'], cwd: root },
    { tool: 'cargo', args: ['check'], cwd: join(root, 'src-tauri') },
  ]);
});

test('a failing lock refresh restores all three manifests and names the command', (t) => {
  const root = makeRepo(t);
  assert.throws(
    () => runBump('0.2.0', { root, exec: () => ({ status: 1 }) }),
    /`npm install --package-lock-only` exited with status 1 — the three manifests are restored to 0\.1\.0/,
  );
  assert.equal(readRepo(root, 'package.json'), PKG);
  assert.equal(readRepo(root, 'src-tauri/Cargo.toml'), CARGO);
  assert.equal(readRepo(root, 'src-tauri/tauri.conf.json'), CONF);
});

test('the second lock command does not run when the first fails', (t) => {
  const root = makeRepo(t);
  const calls = [];
  assert.throws(() =>
    runBump('0.2.0', {
      root,
      exec: (tool, args, cwd) => {
        calls.push({ tool, args, cwd });
        return { status: 1 };
      },
    }),
  );
  assert.equal(calls.length, 1);
  assert.equal(calls[0].tool, 'npm');
});

test('a lock refresh that leaves the old version behind is reported loudly', (t) => {
  const root = makeRepo(t);
  assert.throws(
    () => runBump('0.2.0', { root, exec: () => ({ status: 0 }) }),
    /package-lock\.json is still at 0\.1\.0 after `npm install --package-lock-only`/,
  );
  // No rollback on a verification failure — the surprising state is evidence.
  assert.ok(readRepo(root, 'package.json').includes('"version": "0.2.0"'));
});

test('the report names both locks with their refresh commands and old → new versions', (t) => {
  const root = makeRepo(t);
  const report = bump(root);
  assert.deepEqual(report.locks, [
    { path: 'package-lock.json', command: 'npm install --package-lock-only', from: '0.1.0', to: '0.2.0' },
    { path: 'src-tauri/Cargo.lock', command: 'cargo check', from: '0.1.0', to: '0.2.0' },
  ]);
});
